apiVersion: v1
kind: Service
metadata:
  labels:
    app: account
  name: account
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: account
status:
  loadBalancer: {}
