apiVersion: v1
kind: Service
metadata:
  labels:
    app: account
  name: account
spec:
  type: NodePort
  ports:
    - name: "5000"
      port: 5000
      targetPort: 80
  selector:
    app: account
status:
  loadBalancer: {}
