apiVersion: v1
kind: Service
metadata:
  labels:
    app: bank
  name: bank
spec:
  ports:
    - name: '5004'
      port: 5004
      targetPort: 80
  selector:
    app: bank
status:
  loadBalancer: {}
