apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: stock-web-app.com
      http:
        paths:
          - backend:
              serviceName: web-app
              servicePort: 80
            path: /
          - backend:
              serviceName: account
              servicePort: 5000
            path: /account-api/
