apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
        - image: brunton/web-app
          imagePullPolicy: ''
          name: web-app
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
      serviceAccountName: ''
      volumes: null
status: {}
