apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  ports:
    - name: '4200'
      port: 4200
      targetPort: 80
  selector:
    app: web-app
status:
  loadBalancer: {}
