version: "3"
services:
  web-app:
    container_name: "web-app"
    build: ./WebAppService
    ports:
      - "4200:80"
    depends_on:
      - account
    networks:
      - app-network

  account:
    container_name: "account"
    build: ./AccountService
    restart: on-failure
    ports:
      - "5000:80"
    depends_on:
      - user-db
    networks:
      - app-network

  bank:
    container_name: "bank"
    build: ./BankService
    restart: on-failure
    ports:
      - "5004:80"
    networks:
      - app-network

  user-db:
    image: "mcr.microsoft.com/mssql/server:2017-CU19-ubuntu-16.04"
    container_name: "user-db"
    restart: on-failure
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
      - SA_PASSWORD=Passw0rd
    volumes:
      - user-db-data:/var/opt/mssql/
      - /var/opt/mssql/data
    networks:
      - app-network

  bank-db:
    image: "mcr.microsoft.com/mssql/server:2017-CU19-ubuntu-16.04"
    container_name: "bank-db"
    restart: on-failure
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
      - SA_PASSWORD=Passw0rd
    volumes:
      - bank-db-data:/var/opt/mssql/
      - /var/opt/mssql/data
    networks:
      - app-network

volumes:
  user-db-data:
  bank-db-data:

networks:
  app-network:
