@startuml Auth State Diagram
title Auth State Diagram
skinparam monochrome true

state auth_choice <<choice>>
state login_choice <<choice>>

[*] --> Unauthenticated

Unauthenticated --> auth_choice: WebAppService::login()
auth_choice --> Authenticated: [WebAppService::checkAuth() == true]
auth_choice --> LoggingIn: [WebAppService::checkAuth() == false]


LoggingIn --> login_choice: AccountService::Login(model)
login_choice --> Authenticated : [AccountService::ValidateCredentials(model) == true]
login_choice --> [*] : [AccountService::ValidateCredentials(model) == false]

Authenticated --> Unauthenticated: WebAppService::logout()

@enduml