// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMarketService;

namespace StockMarketService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Stock", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("AmountForSale")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StockMarketService.Models.StockPrice", b =>
                {
                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockName")
                        .HasColumnType("TEXT");

                    b.HasKey("UpdateTime");

                    b.HasIndex("StockName");

                    b.ToTable("StockPrice");
                });

            modelBuilder.Entity("StockMarketService.Models.StockPrice", b =>
                {
                    b.HasOne("Stock", null)
                        .WithMany("HistoricPrice")
                        .HasForeignKey("StockName");
                });
#pragma warning restore 612, 618
        }
    }
}
